#! /bin/bash

# Cron wrapper around the nightly script.  This has to run as root as it
# manipulates the RTC wake alarm and asks upower to suspend.

# First, reset the alarm
DATE=$(date '+%s' -d '3:55am tomorrow')
echo $DATE > /sys/class/rtc/rtc0/wakealarm

# Run the actual script as ross
su --login --command /home/ross/Yocto/poky-nightly/run-nightly ross

# Now, go back to sleep
/home/ross/bin/upower-suspend
