#! /bin/bash

# Cron wrapper around the nightly script.  This has to run as root as it
# manipulates the RTC wake alarm and asks upower to suspend.

# First, reset the alarm
/home/ross/Yocto/poky-nightly/set-alarm

# Run the actual script as ross
su --login --command /home/ross/Yocto/poky-nightly/run-nightly ross

# Now, go back to sleep
/home/ross/bin/upower-suspend
